const translations=window.TRAVEL_TRANSLATIONS||{};const langKey='travel_lang';const currentLang=localStorage.getItem(langKey)||'en';
function applyTranslations(lang){document.documentElement.lang=lang;localStorage.setItem(langKey,lang);document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(translations[lang]&&translations[lang][k])el.textContent=translations[lang][k];});}
function socialLinks(){return '<a href="https://facebook.com" target="_blank" rel="noopener">FB</a><a href="https://instagram.com" target="_blank" rel="noopener">IG</a><a href="https://twitter.com" target="_blank" rel="noopener">X</a><a href="https://youtube.com" target="_blank" rel="noopener">YT</a><a href="https://linkedin.com" target="_blank" rel="noopener">IN</a>';}
function injectGlobalUI(){const h=document.getElementById('site-header'),f=document.getElementById('site-footer');if(h){h.innerHTML='<header class="topbar"><div class="container nav"><a class="brand" href="'+(window.basePath||'./')+'index.html">India Premium Tours</a><nav class="nav-links"><a href="'+(window.basePath||'./')+'index.html">Home</a><a href="'+(window.basePath||'./')+'pages/tours.html">Tours</a><a href="'+(window.basePath||'./')+'pages/golden-triangle.html">Golden Triangle</a><a href="'+(window.basePath||'./')+'pages/blogs.html">Blogs</a><a href="'+(window.basePath||'./')+'pages/reviews.html">Reviews</a><a class="cta" href="'+(window.basePath||'./')+'pages/contact.html">Book Now</a></nav><div class="lang-switcher"><button class="lang-btn" data-lang="en">🇬🇧</button><button class="lang-btn" data-lang="de">🇩🇪</button><button class="lang-btn" data-lang="es">🇪🇸</button><button class="lang-btn" data-lang="it">🇮🇹</button><button class="lang-btn" data-lang="fr">🇫🇷</button></div></div></header>';}
if(f){f.innerHTML='<footer><div class="container footer-grid"><div><h3 data-i18n="brand">India Premium Tours</h3><p data-i18n="footerTag">Trusted India tour operator with verified reviews and secure booking.</p></div><div><h4>Social</h4><div>'+socialLinks()+'</div></div><div><h4>Trust</h4><p>Google • TripAdvisor • Local Guests</p></div></div></footer>';}
if(!document.querySelector('.whatsapp-float')){const wa=document.createElement('div');wa.className='whatsapp-float';wa.innerHTML='<span class="availability">● Available Now</span><a href="https://wa.me/919876543210?text=Hi%2C%20I%20want%20to%20book%20an%20India%20tour" target="_blank" rel="noopener" class="pulse">WhatsApp Chat</a><small style="background:#fff;padding:.2rem .45rem;border-radius:7px">Templates: Quote | Itinerary | Availability</small>';document.body.appendChild(wa);}if(!document.querySelector('.social-floating')){const sf=document.createElement('div');sf.className='social-floating';sf.innerHTML=socialLinks();document.body.appendChild(sf);}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>applyTranslations(b.dataset.lang)));applyTranslations(currentLang);}
function initAnimations(){const io=new IntersectionObserver((entries)=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});document.querySelectorAll('[data-animate]').forEach(el=>io.observe(el));}
document.addEventListener('DOMContentLoaded',()=>{injectGlobalUI();initAnimations();});
